# action.yml
name: "Setup Environment"
description: "UDS Environment Setup"

runs:
  using: "composite"
  steps:
    - name: Install UDS CLI
      shell: bash
      run: |
        curl --retry-all-errors --retry 5 -L https://github.com/defenseunicorns/uds-cli/releases/download/v0.10.4/uds-cli_v0.10.4_Linux_amd64 -o uds
        chmod +x uds
        sudo mv uds /usr/local/bin/
