name: Reusable Test Bundle Workflow

on:
  workflow_call:
    inputs:
      bundle:
        type: string
        description: 'Bundle to test'
        required: true
      runsOn:
        type: string
        description: 'Type of runner that the job will run on'
        required: true
        default: 'ubuntu-latest'

jobs:
  bundle_checks:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Setup runner
        shell: bash
        run: uds run --no-progress setup-env
        env:
          ENVIRONMENT: ${{ inputs.environment }}

      - name: GHCR Login
        run: uds zarf tools registry login -u "dummy" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io

      - name: Test creation of base bundle
        shell: bash
        run: uds run --no-progress create-base

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -${{ inputs.bundle }}
