tasks:
  - name: env
    actions:
      - description: Setup the UDS temp directory
        cmd: |
          test -d /var/tmp/uds || sudo mkdir /var/tmp/uds
          sudo chmod 1777 /var/tmp/uds

      - description: Cleanup single self-hosted runner
        cmd: |
          sudo rm -rf /tmp/zarf-*.log
          sudo rm -rf /tmp/uds-*.log
          sudo rm -rf /var/tmp/zarf-*.log
          sudo rm -rf /var/tmp/uds-*.log
          sudo rm -rf uds-*.tar.zst # Remove outdated bundles

  - name: kubeconfig
    actions:
      - description: Setup the cluster connection (kubeconfig)
        cmd: |
          set -e
          mkdir -p $HOME/.kube
          # NOTE: This must match `cluster_name` in ../terraform/cluster/rke2.tf.
          aws s3 cp s3://uds-$ENVIRONMENT-rke2/rke2.yaml $HOME/.kube/config
          set +e

      - description: Wait for cluster connection
        wait:
          cluster:
            kind: Service
            name: kubernetes
            namespace: default
