options:
  architecture: amd64
  no_progress: true

variables:
  leapfrog-ui:
    domain: https://ai.burning.boats
    model: vllm
  vllm:
    # DO NOT turn off GPU nor reduce the # of GPUs available to this pod, else it will fail
    gpu_enabled: "true"
    requests_gpu: 1
    limits_gpu: 1
  whisper:
    # disabling and reduction of GPU resources is allowed
    gpu_enabled: "true"
    requests_gpu: 1
    limits_gpu: 1
  rag:
    model: vllm
