name: Test Base Bundle
on:
  pull_request:
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  bundle_checks:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Setup runner
        shell: bash
        run: uds run --no-progress setup-env
        env:
          ENVIRONMENT: ${{ inputs.environment }}

      - name: GHCR Login
        run: uds zarf tools registry login -u "dummy" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io

      - name: Test creation of base bundle
        shell: bash
        run: uds run --no-progress create-base

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -base-bundle-checks
